services:
  db:
    container_name: "go-rss-postgres"
    image: postgres:15-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "rss-agg"
      POSTGRES_USER: "localdev"
      POSTGRES_PASSWORD: "password"
    restart: unless-stopped